> hi Robby
Robby sighs metalically and says, "hello, my name is Robby.".

> look
There is a large glass door to the east. The sign says 'Come In!'
There is a key here.
Robby is here.

> take key
You take the key.
A bat enters the Sidewalk via the Glass Door.

> swat bat
The bat flaps frantically up out of your reach.

> go in
        --=(You are in the Vestibule)=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.
A cat is here.


> tell cat follow
cat obediently begins following you
A bat enters the Vestibule via the Glass Door.

> s
        --=(You are in the Office)=--        

A nicely organized office.
There is a door to the north.


> look
A nicely organized office.
There is a door to the north.
A cat is here.

> pet cat
The cat purrs.

> tell cat bark
The cat barks and coughs and something splats on the floor.

> look
A nicely organized office.
There is a door to the north.
There is a hairball here.
A cat is here.

> n
        --=(You are in the Vestibule)=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.
A bat is here.

A bat leaves the Vestibule via the Office Door.

> tell cat bark
The cat barks and coughs and something splats on the floor.

> look
A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.
There is a hairball here.
A cat is here.

> out
        --=(You are in the Sidewalk)=--        

There is a large glass door to the east. The sign says 'Come In!'
Robby is here.


> look
There is a large glass door to the east. The sign says 'Come In!'
A cat is here.
Robby is here.

> tell cat stay
cat obediently stops following you

> look
There is a large glass door to the east. The sign says 'Come In!'
A cat is here.
Robby is here.

> end
