> in
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> s
        --=( Office )=--        

A nicely organized office.
There is a door to the north.
There is a file cabinet here.


> examine file cabinet
You see a rusty old metal file cabinet The file cabinet is closed..

> open file cabinet
It's locked! You will need a key.

> n
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> out
        --=( Sidewalk )=--        

There is a large glass door to the east. The sign says 'Come In!'
There is a key here.


> take key
You take the key.

> in
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> s
        --=( Office )=--        

A nicely organized office.
There is a door to the north.
There is a file cabinet here.


> open file cabinet
You use the a key, the file cabinet unlocks
The file cabinet opens.

There is a secret plan in the file cabinet.

> examine secret plan
You see secret plans to convert Brightworks into a
military academy for cyber-warfare specialists.

> take secret plan
You take the secret plan.

> i
You are carrying a secret plan and a key.

> end
