> look
There is a large glass door to the east. The sign says 'Come In!'
There is a vial here.
A cat is here.

> examine vial
You see a small vial of dark sinister looking liquid.

> tell cat drink vial
Cat drinks a small vial of dark sinister looking liquid.
Cat is choking violently and collapsing onto the floor...
Cat is dead.

> look
There is a large glass door to the east. The sign says 'Come In!'
There is an empty vial here.
A cat is lying here dead as a doornail.

> examine empty vial
You see an empty vial with an acrid odor.

> end
