> give monkey banana
The monkey takes the banana and drops a set of keys

> take keys
You take the keys.

> i
You are carrying keys.

> look
There is a large glass door to the east. The sign says 'Come In!'
A monkey is here.

> give monkey keys
The monkey takes the keys and drops a banana

> look
There is a large glass door to the east. The sign says 'Come In!'
There is a banana here.
A monkey is here.

> eat banana
You eat a nice ripe banana.
mmmmm, banana!

> give monkey banana
Huh?

> give monkey banana peel
Huh?

> end
