> in
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> s
        --=( Office )=--        

A nicely organized office."
There is a door to the north.
There are a few things here: a plate of food, a donut, and a glass of water.


> examine donut
You see a chocolate covered donut with pink sprinkles.

> examine plate of food
You see a plate of green eggs and ham.

> examine glass of water
You see a glass of water, half full.

> drink plate of food
You can't drink the plate of food.

> eat plate of food
You eat a plate of green eggs and ham.
You like them!

> eat plate of food
You can't eat the plate.

> drink glass of water
You drink a glass of water, half full.
You feel refreshed, and strangely optimistic.

> examine glass of water
You see an empty glass.

> drink glass
You can't drink the glass.

> end
