> in
        --=(You are in the Vestibule)=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> s
        --=(You are in the Office)=--        

A nicely organized office."
There is a door to the north.
There are a few things here: a plate and a glass.


> examine plate
You see plate of green eggs and ham.

> examine glass
You see a glass of water, half full

> drink plate
you can't drink the plate.

> eat plate
You eat the plate of green eggs and ham..
You like them!

> eat plate
The plate is empty

> drink glass
You drink the a glass of water, half full.
You feel refreshed, and strangely optimistic

> examine glass
You see an empty glass

> drink glass
The glass is empty

> end
