> flip coin
The coin is on the ground!

> take coin
You take the coin.

> flip coin
The coin shows tails.

> flip coin
The coin shows tails.

> flip coin
The coin shows heads.

> flip coin
The coin shows tails.

> flip coin
The coin shows tails.

> flip coin
The coin shows tails.

> flip coin
The coin shows heads.

> flip coin
The coin shows tails.

> flip coin
The coin shows tails.

> take key
You take the key.

> rub key
You rub the key, but fail to shine it.

> go in
You use the a key, the Vestibule unlocks
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.
There is a hairpin here.


> go s
It's locked!
Bonk! you can't seem to go that way.
Huh?

> take hairpin
You take the hairpin.

> pick lock
you slip the hairpin into the lock and skillfully pick it open

> s
        --=( Office )=--        

A nicely organized office.
There is a door to the north.


> n
        --=( Vestibule )=--        

A small area at the bottom of a flight of stairs.
There is a glass door to the west and door to the south.


> go out
        --=( Sidewalk )=--        

There is a large glass door to the east. The sign says 'Come In!'


> drop key

> drop coin

> look
There is a large glass door to the east. The sign says 'Come In!'
There are a few things here: a coin and a key.

> take coin
You take the coin.

> inventory
You are carrying a coin and a hairpin.

> flip coin
The coin shows tails.

> drop coin

> end
